"""changes for models

Revision ID: 4ed4d8596a65
Revises: d909de7fd86b
Create Date: 2024-11-20 23:07:03.568067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed4d8596a65'
down_revision = 'd909de7fd86b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phrases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('browsers_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('phrases_browers_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'browsers', ['browsers_id'], ['id'])
        batch_op.drop_column('browers_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phrases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('browers_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('phrases_browers_id_fkey', 'browsers', ['browers_id'], ['id'])
        batch_op.drop_column('browsers_id')

    # ### end Alembic commands ###
