"""add column for phrases

Revision ID: bdb5f7786d65
Revises: 705a0b0d6606
Create Date: 2024-09-16 23:49:28.881630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdb5f7786d65'
down_revision = '705a0b0d6606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phrases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('translation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phrases', schema=None) as batch_op:
        batch_op.drop_column('translation')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
