"""changes on table phrases and create table browsers

Revision ID: d909de7fd86b
Revises: 2ae13716938f
Create Date: 2024-11-20 22:41:38.960390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd909de7fd86b'
down_revision = '2ae13716938f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('browsers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phrases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('browers_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'browsers', ['browers_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phrases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('browers_id')

    op.drop_table('browsers')
    # ### end Alembic commands ###
